package com.org.backend.enums;

public enum Permission {
    DEPARTMENT_VIEW_ALL,
    DEPARTMENT_CREATE,
    DEPARTMENT_UPDATE,
    POSITION_CREATE,
    POSITION_UPDATE,
    EMPLOYEE_CREATE,
    EMPLOYEE_UPDATE,
    EMPLOYEE_VIEW_ALL,
    EMPLOYEE_VIEW_TEAM,
    EMPLOYEE_VIEW_SELF,
    EMPLOYEE_SEARCH,
    HIERARCHY_VIEW,
    HIERARCHY_EDIT,
    TASK_CREATE,
    TASK_UPDATE,
    TASK_DELETE,
    TASK_VIEW,
    TASK_ASSIGN,
    TASK_COMMENT
}
